### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by adameus03** [adameus03/spc-cloud#1]
## Some of the issues to be resolved:
- [ ] Configure HTTPS + forbid HTTP
- [x] Stopping the Azure container doesn't result in data loss (use Azure file storage?)
- [x] Integrate a ~~PostreSQL~~SQLite database to store user authentication data (incorporate Docker Compose ~~to upgrade the app into a multi-container app?~~ to simplify the build process and enable File Share volume mount)
- [ ] Make a good client GUI
- [x] Use an unique identifier as a ~~filename for any file~~ name for container directory for files uploaded by users
- [x] Store the  file identifiers in the database and map them to user paths
- [x] Make files accessible only for the authorized users
- [x] Handle custom file permissions & file sharing
- [x] List user files
- [x] Bypass variable public IP (FQDN?)

**Comment by adameus03** [comment]
SQLite database accessible, but not yet storing the user data (do not confuse with files uploaded by  users, which are stored in the persistent Azure File Share volume)
